export enum EmailTemplates {
  // Authentication
  USER_REGISTRATION_CONFIRMATION = 'USER_REGISTRATION_CONFIRMATION',
  RESEND_VERIFICATION_EMAIL = 'RESEND_VERIFICATION_EMAIL',
  RESET_PASSWORD_CODE = 'RESET_PASSWORD_CODE',
  PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS',

  // General
  PRIVACY_POLICY_UPDATE = 'PRIVACY_POLICY_UPDATE',

  // Order
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_SHIPPED = 'ORDER_SHIPPED',
  ORDER_OUT_FOR_DELIVERY = 'ORDER_OUT_FOR_DELIVERY',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_DELIVERY_FAILED = 'ORDER_DELIVERY_FAILED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_RETURNED = 'ORDER_RETURNED',
}
