import { CronExpression } from "@nestjs/schedule";

export const CRON_JOBS = {
  BANNER: {
    DEACTIVATE_EXPIRED_BANNERS: CronExpression.EVERY_HOUR,
  },
  PRODUCT: {
    RESET_WEEKLY_STATS: CronExpression.EVERY_WEEK,
  },
  TYPE_HINT: {
    DEACTIVATE_EXPIRED_TYPE_HINTS: CronExpression.EVERY_HOUR,
  },
  SHOWCASE: {
    CHECK_INACTIVE_TYPE_HINT: CronExpression.EVERY_HOUR,
  },
  MEDIA: {
    // PURGE_DELETED_MEDIA: CronExpression.EVERY_WEEK,
    PURGE_DELETED_MEDIA: CronExpression.EVERY_10_SECONDS,
    PURGE_DELETED_MEDIA_THRESHOLD_IN_DAYS: 7,
    PURGE_DELETED_MEDIA_THRESHOLD_SECONDS:  10,
  }
};
