export const ApiPaths = {
  Authentication: {
    Root: 'api/v1/authentication',
    Register: 'register',
    VerifyEmail: 'verify-email',
    ResendVerificationEmail: 'resend-verification-email',
    ForgotPassword: {
      Root: 'forgot-password',
      SendIdentifier: 'send-identifier',
      VerifyResetPasswordCode: 'verify-reset-password-code',
      ResetPassword: 'reset-password',
    },
  },
  Authorization: {
    Root: 'api/v1/authorization',
    Login: 'login',
  },
  Banner: {
    Root: '/api/v1/banner',
    GetAll: 'all',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  Category: {
    Root: '/api/v1/category',
    GetAll: 'all',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  Product: {
    Root: '/api/v1/product',
    Create: 'create',
    Update: 'update/:id',
    GetAll: 'all',
    Suggested: 'suggested',
    CategoriesPicks: 'categories-picks',
    GetOne: ':id',
    UpdateStatus: 'status/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
  },
  Search: {
    Root: '/api/v1/search',
    Products: 'products',
  },
  Comment: {
    Root: '/api/v1/comment',
    All: 'all',
    One: 'one/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
  },
  Location: {
    Root: 'api/v1/location',
    BulkUpload: 'bulk-upload',
    GetAll: 'all',
    Delete: 'delete/:id',
  },
  Logo: {
    Root: '/api/v1/logo',
    GetAll: 'all',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  Showcase: {
    Root: '/api/v1/showcase',
    GetAll: 'all',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  Media: {
    Root: 'api/v1/media',
    Upload: 'upload',
    GetOne: 'file/:fileId',
  },
  SubCategory: {
    Root: '/api/v1/sub-category',
    GetAll: 'all',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  TypeHintConfig: {
    Root: '/api/v1/type-hint-config',
    GetAll: 'all',
    GetList: 'list',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    Update: 'update/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  User: {
    Root: '/api/v1/user',
    GetAll: 'all',
    GetStats: 'stats',
    GetActiveOnes: 'active',
    GetOne: '/:id',
    Create: 'create',
    CreateAdmin: 'create-admin',
    Update: 'update/:id',
    UpdateAdmin: 'update-admin/:id',
    Delete: 'delete/:id',
    UnDelete: 'un-delete/:id',
    UpdateStatus: 'status/:id',
  },
  Wishlist: {
    Root: '/api/v1/wish-list',
    GetWishlist: '/',
    AddOne: 'add',
    RemoveOne: 'remove',
    RemoveAll: 'remove-all',
    SendToCart: 'send-to-cart',
    SendAllToCart: 'send-all-to-cart',
  },
  Cart: {
    Root: '/api/v1/cart',
    GetCart: '/',
    AddOne: 'add',
    RemoveOne: 'remove',
    RemoveAll: 'remove-all',
    WishlistItems: 'wishlist-items',
  },
  Nationality: {
    Root: '/api/v1/nationality',
    GetAll: 'all',
    GetAllStatic: 'all-static',
  },
  Payment: {
    Root: '/api/v1/payment',
    ProcessPayment: 'process',
    VerifyPayment: 'verify',
    Checkout: 'checkout',
  },
};
