export const SYSTEM_TYPE_HINTS = [
  {
    key: 'static',
    label: { en: 'Static', ar: 'أساسي' },
    isSystem: true,
    isActive: true,
    priority: 1,
    createdBy: process.env.DB_SYSTEM_OBJ_ID,
    updatedBy: process.env.DB_SYSTEM_OBJ_ID,
  },
  {
    key: 'best_sellers',
    label: { en: 'Best Sellers', ar: 'الأفضل مبيعاً' },
    isSystem: true,
    isActive: true,
    priority: 2,
    createdBy: process.env.DB_SYSTEM_OBJ_ID,
    updatedBy: process.env.DB_SYSTEM_OBJ_ID,
  },
  {
    key: 'most_viewed',
    label: { en: 'Most Viewed', ar: 'الأكثر مشاهدة' },
    isSystem: true,
    isActive: true,
    priority: 3,
    createdBy: process.env.DB_SYSTEM_OBJ_ID,
    updatedBy: process.env.DB_SYSTEM_OBJ_ID,
  },
  {
    key: 'picked',
    label: { en: 'Picked Items', ar: 'عناصر مختارة' },
    isSystem: true,
    isActive: true,
    priority: 4,
    createdBy: process.env.DB_SYSTEM_OBJ_ID,
    updatedBy: process.env.DB_SYSTEM_OBJ_ID,
  },
  {
    key: 'recommended',
    label: { en: 'Recommended', ar: 'مقترحاتنا' },
    isSystem: true,
    isActive: true,
    priority: 5,
    createdBy: process.env.DB_SYSTEM_OBJ_ID,
    updatedBy: process.env.DB_SYSTEM_OBJ_ID,
  },
];
